// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Restaurant struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Rating               float32  `protobuf:"fixed32,2,opt,name=Rating,proto3" json:"Rating,omitempty"`
	Cuisines             string   `protobuf:"bytes,3,opt,name=Cuisines,proto3" json:"Cuisines,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	CFT                  int32    `protobuf:"varint,5,opt,name=CFT,proto3" json:"CFT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Restaurant) GetCuisines() string {
	if m != nil {
		return m.Cuisines
	}
	return ""
}

func (m *Restaurant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Restaurant) GetCFT() int32 {
	if m != nil {
		return m.CFT
	}
	return 0
}

type RequestOne struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestOne) Reset()         { *m = RequestOne{} }
func (m *RequestOne) String() string { return proto.CompactTextString(m) }
func (*RequestOne) ProtoMessage()    {}
func (*RequestOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *RequestOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOne.Unmarshal(m, b)
}
func (m *RequestOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOne.Marshal(b, m, deterministic)
}
func (m *RequestOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOne.Merge(m, src)
}
func (m *RequestOne) XXX_Size() int {
	return xxx_messageInfo_RequestOne.Size(m)
}
func (m *RequestOne) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOne.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOne proto.InternalMessageInfo

func (m *RequestOne) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseAllRes struct {
	ResList              []*Restaurant `protobuf:"bytes,1,rep,name=resList,proto3" json:"resList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseAllRes) Reset()         { *m = ResponseAllRes{} }
func (m *ResponseAllRes) String() string { return proto.CompactTextString(m) }
func (*ResponseAllRes) ProtoMessage()    {}
func (*ResponseAllRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *ResponseAllRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAllRes.Unmarshal(m, b)
}
func (m *ResponseAllRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAllRes.Marshal(b, m, deterministic)
}
func (m *ResponseAllRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAllRes.Merge(m, src)
}
func (m *ResponseAllRes) XXX_Size() int {
	return xxx_messageInfo_ResponseAllRes.Size(m)
}
func (m *ResponseAllRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAllRes.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAllRes proto.InternalMessageInfo

func (m *ResponseAllRes) GetResList() []*Restaurant {
	if m != nil {
		return m.ResList
	}
	return nil
}

type RequestAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAll) Reset()         { *m = RequestAll{} }
func (m *RequestAll) String() string { return proto.CompactTextString(m) }
func (*RequestAll) ProtoMessage()    {}
func (*RequestAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *RequestAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAll.Unmarshal(m, b)
}
func (m *RequestAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAll.Marshal(b, m, deterministic)
}
func (m *RequestAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAll.Merge(m, src)
}
func (m *RequestAll) XXX_Size() int {
	return xxx_messageInfo_RequestAll.Size(m)
}
func (m *RequestAll) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAll.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAll proto.InternalMessageInfo

type Nresponse struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nresponse) Reset()         { *m = Nresponse{} }
func (m *Nresponse) String() string { return proto.CompactTextString(m) }
func (*Nresponse) ProtoMessage()    {}
func (*Nresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *Nresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nresponse.Unmarshal(m, b)
}
func (m *Nresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nresponse.Marshal(b, m, deterministic)
}
func (m *Nresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nresponse.Merge(m, src)
}
func (m *Nresponse) XXX_Size() int {
	return xxx_messageInfo_Nresponse.Size(m)
}
func (m *Nresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Nresponse.DiscardUnknown(m)
}

var xxx_messageInfo_Nresponse proto.InternalMessageInfo

func (m *Nresponse) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func init() {
	proto.RegisterType((*Restaurant)(nil), "proto.Restaurant")
	proto.RegisterType((*RequestOne)(nil), "proto.requestOne")
	proto.RegisterType((*ResponseAllRes)(nil), "proto.responseAllRes")
	proto.RegisterType((*RequestAll)(nil), "proto.requestAll")
	proto.RegisterType((*Nresponse)(nil), "proto.nresponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xfe, 0xa4, 0xed, 0xe5, 0x47, 0xc5, 0x08, 0x64, 0x65, 0x21, 0xf2, 0x14, 0x09,
	0xa9, 0xad, 0xca, 0xc0, 0xc4, 0x10, 0x55, 0x62, 0x42, 0x20, 0x19, 0x5e, 0xc0, 0x90, 0x4b, 0x64,
	0xc9, 0x75, 0x8a, 0xed, 0x32, 0x30, 0xf1, 0xa2, 0xbc, 0x0b, 0x8a, 0xdb, 0x24, 0x05, 0x16, 0xa6,
	0x9c, 0x73, 0x63, 0xdf, 0xef, 0x1c, 0xc3, 0xe9, 0xda, 0x96, 0xbe, 0x9c, 0x39, 0xb4, 0xef, 0xea,
	0x05, 0xa7, 0xc1, 0xd1, 0x41, 0xf8, 0xf0, 0x4f, 0x02, 0x20, 0xd0, 0x79, 0xb9, 0xb1, 0xd2, 0x78,
	0x4a, 0xa1, 0x7f, 0x2f, 0x57, 0xc8, 0x48, 0x42, 0xd2, 0xb1, 0x08, 0x9a, 0x9e, 0x43, 0x24, 0xa4,
	0x57, 0xa6, 0x60, 0xdd, 0x84, 0xa4, 0x5d, 0xb1, 0x73, 0x34, 0x86, 0xd1, 0x72, 0xa3, 0x9c, 0x32,
	0xe8, 0x58, 0x2f, 0x9c, 0x6f, 0x3c, 0x65, 0x30, 0xcc, 0xf2, 0xdc, 0xa2, 0x73, 0xac, 0x1f, 0x7e,
	0xd5, 0x96, 0x4e, 0xa0, 0xb7, 0xbc, 0x7d, 0x62, 0x83, 0x84, 0xa4, 0x03, 0x51, 0x49, 0x9e, 0x00,
	0x58, 0x7c, 0xdb, 0xa0, 0xf3, 0x0f, 0x06, 0xab, 0x04, 0x66, 0x2f, 0x41, 0xa5, 0xf9, 0x0d, 0x1c,
	0x5b, 0x74, 0xeb, 0xd2, 0x38, 0xcc, 0xb4, 0x16, 0xe8, 0xe8, 0x25, 0x0c, 0x2d, 0xba, 0x3b, 0xe5,
	0x3c, 0x23, 0x49, 0x2f, 0x3d, 0x58, 0x9c, 0x6c, 0x6b, 0x4d, 0xdb, 0x2e, 0xa2, 0x3e, 0xc1, 0x0f,
	0x1b, 0x40, 0xa6, 0x35, 0xbf, 0x80, 0xb1, 0xa9, 0xb7, 0x55, 0xb4, 0x57, 0x2d, 0x8b, 0x40, 0x1b,
	0x89, 0xa0, 0x17, 0x5f, 0x04, 0x8e, 0x3e, 0xca, 0x95, 0xf4, 0xe5, 0xe3, 0xf6, 0xc5, 0xe8, 0x1c,
	0xa2, 0x02, 0x7d, 0xc5, 0xad, 0x31, 0x6d, 0xe0, 0xf8, 0x2f, 0x99, 0x77, 0xe8, 0x35, 0x8c, 0x0b,
	0xf4, 0xbb, 0xb0, 0xbf, 0x2e, 0x65, 0x5a, 0xc7, 0x67, 0xcd, 0x68, 0xbf, 0x16, 0xef, 0xd0, 0x39,
	0x0c, 0x31, 0x57, 0x3f, 0x58, 0xed, 0xe2, 0x78, 0xb2, 0x1b, 0x35, 0x05, 0x78, 0x87, 0xce, 0x20,
	0x92, 0x79, 0xfe, 0xff, 0x0b, 0xcf, 0x51, 0x18, 0x5d, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe5,
	0x4a, 0xe4, 0xe1, 0x17, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZomatoServiceClient is the client API for ZomatoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZomatoServiceClient interface {
	GetRes(ctx context.Context, in *RequestOne, opts ...grpc.CallOption) (*Restaurant, error)
	GetAllRes(ctx context.Context, in *RequestAll, opts ...grpc.CallOption) (*ResponseAllRes, error)
	EditRes(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*Nresponse, error)
	AddRes(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*Nresponse, error)
}

type zomatoServiceClient struct {
	cc *grpc.ClientConn
}

func NewZomatoServiceClient(cc *grpc.ClientConn) ZomatoServiceClient {
	return &zomatoServiceClient{cc}
}

func (c *zomatoServiceClient) GetRes(ctx context.Context, in *RequestOne, opts ...grpc.CallOption) (*Restaurant, error) {
	out := new(Restaurant)
	err := c.cc.Invoke(ctx, "/proto.zomatoService/getRes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zomatoServiceClient) GetAllRes(ctx context.Context, in *RequestAll, opts ...grpc.CallOption) (*ResponseAllRes, error) {
	out := new(ResponseAllRes)
	err := c.cc.Invoke(ctx, "/proto.zomatoService/getAllRes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zomatoServiceClient) EditRes(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*Nresponse, error) {
	out := new(Nresponse)
	err := c.cc.Invoke(ctx, "/proto.zomatoService/editRes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zomatoServiceClient) AddRes(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*Nresponse, error) {
	out := new(Nresponse)
	err := c.cc.Invoke(ctx, "/proto.zomatoService/addRes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZomatoServiceServer is the server API for ZomatoService service.
type ZomatoServiceServer interface {
	GetRes(context.Context, *RequestOne) (*Restaurant, error)
	GetAllRes(context.Context, *RequestAll) (*ResponseAllRes, error)
	EditRes(context.Context, *Restaurant) (*Nresponse, error)
	AddRes(context.Context, *Restaurant) (*Nresponse, error)
}

// UnimplementedZomatoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedZomatoServiceServer struct {
}

func (*UnimplementedZomatoServiceServer) GetRes(ctx context.Context, req *RequestOne) (*Restaurant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRes not implemented")
}
func (*UnimplementedZomatoServiceServer) GetAllRes(ctx context.Context, req *RequestAll) (*ResponseAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRes not implemented")
}
func (*UnimplementedZomatoServiceServer) EditRes(ctx context.Context, req *Restaurant) (*Nresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRes not implemented")
}
func (*UnimplementedZomatoServiceServer) AddRes(ctx context.Context, req *Restaurant) (*Nresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRes not implemented")
}

func RegisterZomatoServiceServer(s *grpc.Server, srv ZomatoServiceServer) {
	s.RegisterService(&_ZomatoService_serviceDesc, srv)
}

func _ZomatoService_GetRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOne)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoServiceServer).GetRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.zomatoService/GetRes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoServiceServer).GetRes(ctx, req.(*RequestOne))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZomatoService_GetAllRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoServiceServer).GetAllRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.zomatoService/GetAllRes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoServiceServer).GetAllRes(ctx, req.(*RequestAll))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZomatoService_EditRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoServiceServer).EditRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.zomatoService/EditRes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoServiceServer).EditRes(ctx, req.(*Restaurant))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZomatoService_AddRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZomatoServiceServer).AddRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.zomatoService/AddRes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZomatoServiceServer).AddRes(ctx, req.(*Restaurant))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZomatoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.zomatoService",
	HandlerType: (*ZomatoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getRes",
			Handler:    _ZomatoService_GetRes_Handler,
		},
		{
			MethodName: "getAllRes",
			Handler:    _ZomatoService_GetAllRes_Handler,
		},
		{
			MethodName: "editRes",
			Handler:    _ZomatoService_EditRes_Handler,
		},
		{
			MethodName: "addRes",
			Handler:    _ZomatoService_AddRes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
