<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.responseAllRes</code>
 */
class responseAllRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.Restaurant resList = 1;</code>
     */
    private $resList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Restaurant[]|\Google\Protobuf\Internal\RepeatedField $resList
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Restaurant resList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResList()
    {
        return $this->resList;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Restaurant resList = 1;</code>
     * @param \Proto\Restaurant[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Restaurant::class);
        $this->resList = $arr;

        return $this;
    }

}

